draw_bold_text_with_bight_colors = true
live_config_reload = true

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[scrolling]
history = 10000

[window]
border = "none"
opacity = 0.7
blur = true


[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5
